# Use the official Postgres image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB yourdbname
ENV POSTGRES_USER yourdbuser
ENV POSTGRES_PASSWORD yourdbpassword
#RUN chmod 777 /var/lib/postgresql/data